src/archaeology/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('site/create', views.create_site, name='addsite'),
    path('site', views.list_sites, name='list_sites'),
    path('site/<int:pk>', views.view_site, name='view_site'),
    path('site/<int:pk>/update', views.update_site, name='update_site'),
    path('site/<int:pk>/import', views.import_occurrences, name='import_occurrences'),
    path('site/<int:pk>/delete', views.delete_site, name='delete_site'),
    path('occurrence', views.list_occurrences, name='list_occurrences'),
    path('occurrence/<int:pk>/create', views.create_occurrence, name='create_occurrence'),
    path('occurrence/<int:pk>', views.view_occurrence, name='view_occurrence'),
    path('occurrence/<int:pk>/update', views.update_occurrence, name='update_occurrence'),
    path('occurrence/<int:pk>/delete', views.delete_occurrence, name='delete_occurrence'),
    path('identification', views.identification_aoi, name='identification_aoi'),
    path('identification/layers', views.identification_layers, name='identification_layers'),
    path('execution', views.executions_history, name='executions_history'),
    path('execution/<int:pk>', views.view_execution, name='view_execution'),
    path('execution/<int:pk>/delete', views.delete_execution, name='delete_execution'),
    ]
 

src/geonode_odyssey/urls.py
# -*- coding: utf-8 -*-
#########################################################################
#
# Copyright (C) 2017 OSGeo
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################

from django.conf.urls import url, include
from django.views.generic import TemplateView
from django.urls import include, path
from geonode.urls import urlpatterns
from geonode.base import register_url_event
from . import views

urlpatterns += [
    url(r'^archaeology/', include('archaeology.urls')),
    path("select2/", include("django_select2.urls")),
    path('about/project', TemplateView.as_view(template_name='about_project.html'), name="about_project"),
]

urlpatterns = [
    url(r'^/?$',
        views.index,
        name='home'),
 ] + urlpatterns

src/archaeology/models.py
# Create your models here.
from django.contrib.gis.db import models
from django.conf import settings
from django.forms import ValidationError
from django.urls import reverse
from django_countries.fields import CountryField
from geonode.documents.models import Document
from geonode.layers.models import LayerFile
from django.utils.translation import ugettext_lazy

# Create your models here.
class AlgorithmExecution(models.Model):
    """Model representing an execution of the automatic identification algorithm."""
    
    STATUS_CHOICES = (
    ("E", ugettext_lazy("Executing")),
    ("F", ugettext_lazy("Finished")))

    PURPOSE_CHOICES = (
    ("training", ugettext_lazy("Training")),
    ("inference", ugettext_lazy("Inference")))

    name = models.CharField(max_length=254, verbose_name=ugettext_lazy('Name'))
    executed_at = models.DateTimeField(auto_now_add = True, verbose_name=ugettext_lazy('Executed at'))
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default="E", verbose_name=ugettext_lazy('Status'))
    purpose = models.CharField(max_length=15, choices=PURPOSE_CHOICES, default="inference", verbose_name=ugettext_lazy('Purpose'))
    executed_by = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.SET_NULL, verbose_name=ugettext_lazy('Executed by'))
    layers_used = models.ManyToManyField(LayerFile, verbose_name=ugettext_lazy('Layers Used'))
    aoi = models.PolygonField(verbose_name=ugettext_lazy('Area of Interest'))

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        """Returns the url to access a particular archaeological site."""
        return reverse('view_execution', args=[str(self.id)])

    class Meta:
        db_table = 'algorithm_execution'
        verbose_name = ugettext_lazy('Algorithm Execution')
        verbose_name_plural = ugettext_lazy('Algorithm Executions')
        ordering = ['-executed_at']

class AttributeCategory(models.Model):
    """Model representing a category for an attribute (e.g. chronology, geological context)."""
    name = models.CharField(max_length=254, verbose_name=ugettext_lazy('Name'))

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'attribute_category'
        verbose_name = ugettext_lazy('Attribute Category')
        verbose_name_plural = ugettext_lazy('Attribute Categories')
        ordering = ['name']

class AttributeChoice(models.Model):
    """Model to represent a choice option for an attribute category (e.g. for Chronology: neolithic, full bronze)."""
    category = models.ForeignKey(AttributeCategory, on_delete=models.CASCADE, verbose_name=ugettext_lazy('Category'))
    value = models.CharField(max_length=254, verbose_name=ugettext_lazy('Value'))

    def __str__(self):
        return '{0}: {1}'.format(self.category, self.value)

    class Meta:
        db_table = 'attribute_choice'
        verbose_name = ugettext_lazy('Attribute Choice')
        verbose_name_plural = ugettext_lazy('Attribute Choices')
        ordering = ['category', 'value']

class Site(models.Model):
    """Model representing an archaeological site."""

    STATE_CHOICES = (
        ("N", ugettext_lazy("Not Verified")),
        ("V", ugettext_lazy("Verified")))

    name = models.CharField(max_length=254, verbose_name=ugettext_lazy('Name'))
    national_site_code = models.IntegerField(null=True, blank=True, unique=True, verbose_name=ugettext_lazy('National Site Code'))
    country_iso = CountryField(verbose_name=ugettext_lazy('Country'), default="PT")
    parish = models.CharField(max_length=254, blank=True, verbose_name=ugettext_lazy('Parish'))
    location = models.PointField(null=True, blank=True, verbose_name=ugettext_lazy('Location'))
    surrounding_polygon = models.PolygonField(null=True, blank=True, verbose_name=ugettext_lazy('Surrounding Polygon'))
    added_by = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.SET_NULL, verbose_name=ugettext_lazy('Added by'))
    document_site = models.ManyToManyField(Document, blank=True, verbose_name=ugettext_lazy('documents'))
    attribute_site = models.ManyToManyField(AttributeChoice, blank=True, verbose_name=ugettext_lazy('attributes'))
    created_by_execution = models.ForeignKey(AlgorithmExecution, null=True, on_delete=models.SET_NULL, default=None, verbose_name=ugettext_lazy('Created by execution'))
    status_site = models.CharField(max_length=1, choices=STATE_CHOICES, default="V", verbose_name=ugettext_lazy('Status'))

    def __str__(self):  
        return self.name

    def get_absolute_url(self):
        """Returns the url to access a particular archaeological site."""
        return reverse('view_site', args=[str(self.id)])

    def clean(self):
        # Checks if at least one of the spatial fields is filled in (Model Level)
        if not self.location and not self.surrounding_polygon:
            raise ValidationError(ugettext_lazy('At least one of the spatial fields (point or polygon) is required.'))
    
    class Meta:
        db_table = 'site'
        verbose_name = ugettext_lazy('Site')
        verbose_name_plural = ugettext_lazy('Sites')
        ordering = ['national_site_code', 'name']
        # Checks if at least one of the spatial fields is filled in (DB Level)
        constraints = [
            models.CheckConstraint(
                name="Site_location_and_or_surrounding_polygon",
                check=(
                    models.Q(location__isnull=False)
                    | models.Q(surrounding_polygon__isnull=False)
                ),
            )
        ]

class Occurrence(models.Model):
    """Model representing an archaeological occurrence within a site."""

    STATE_CHOICES_OCCURRENCE = (
        ("N", ugettext_lazy("Not Verified")),
        ("V", ugettext_lazy("Verified")),
        ("T", ugettext_lazy("Verified - True Positive")),
        ("F", ugettext_lazy("Verified - False Positive")))

    designation = models.CharField(max_length=254, verbose_name=ugettext_lazy('Designation'))
    acronym = models.CharField(max_length=254, blank=True, verbose_name=ugettext_lazy('Acronym'))
    toponym = models.CharField(max_length=254, blank=True, verbose_name=ugettext_lazy('Toponym'))
    owner = models.CharField(max_length=254, blank=True, verbose_name=ugettext_lazy('Owner'))
    altitude = models.IntegerField(null=True, blank=True, verbose_name=ugettext_lazy('Altitude'))
    position = models.PointField(null=True, blank=True, verbose_name=ugettext_lazy('Position'))
    bounding_polygon = models.PolygonField(null=True, blank=True, verbose_name=ugettext_lazy('Bounding Polygon'))
    site = models.ForeignKey(Site, on_delete=models.CASCADE, verbose_name=ugettext_lazy('Site'))
    added_by = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.SET_NULL, verbose_name=ugettext_lazy('Added by'))
    document_occurrence = models.ManyToManyField(Document, blank=True, verbose_name=ugettext_lazy('documents'))
    attribute_occurrence = models.ManyToManyField(AttributeChoice, blank=True, verbose_name=ugettext_lazy('attributes'))
    algorithm_execution = models.ForeignKey(AlgorithmExecution, null=True, on_delete=models.SET_NULL, default=None, verbose_name=ugettext_lazy('Created by execution'))
    status_occurrence = models.CharField(max_length=1, choices=STATE_CHOICES_OCCURRENCE, default="V", verbose_name=ugettext_lazy('Status'))

    def __str__(self):
        return self.designation

    def clean(self):
        # Checks if at least one of the spatial fields is filled in (Model Level)
        if not self.position and not self.bounding_polygon:
            raise ValidationError(ugettext_lazy('At least one of the spatial fields (point or polygon) is required.'))

    def get_absolute_url(self):
        """Returns the url to access a particular occurrence."""
        return reverse('view_occurrence', args=[str(self.id)])

    class Meta:
        db_table = 'occurrence'
        verbose_name = ugettext_lazy('Occurrence')
        verbose_name_plural = ugettext_lazy('Occurrences')
        ordering = ['designation']
        # Checks if at least one of the spatial fields is filled in (DB Level)
        constraints = [
            models.CheckConstraint(
                name="Occurrence_position_and_or_bounding_polygon",
                check=(
                    models.Q(position__isnull=False)
                    | models.Q(bounding_polygon__isnull=False)
                ),
            )
        ]

class MetricType(models.Model):
    """Model representing a type of metric (e.g. area, width, height)."""
    name = models.CharField(max_length=254, verbose_name=ugettext_lazy('Name'))

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'metric_type'
        verbose_name = ugettext_lazy('Metric Type')
        verbose_name_plural = ugettext_lazy('Metric Types')
        ordering = ['name']

class Metric(models.Model):
    """Model representing a metric of an occurrence."""
    type = models.ForeignKey(MetricType, on_delete=models.PROTECT, verbose_name=ugettext_lazy('Type'))
    occurrence = models.ForeignKey(Occurrence, on_delete=models.CASCADE, verbose_name=ugettext_lazy('Occurrence'))
    auto_value = models.DecimalField(verbose_name=ugettext_lazy('automatic value'), max_digits= 10, decimal_places=2, null=True, blank=True)
    confirmed_value = models.DecimalField(max_digits= 10, decimal_places=2, null=True, blank=True, verbose_name=ugettext_lazy('Confirmed Value'))
    unit_measurement = models.CharField(verbose_name=ugettext_lazy('unit of measurement'), max_length=50, null=True, blank=True)

    def __str__(self):
        if self.confirmed_value:
            return '{0} ({1}) = {2} {3}'.format(self.type, self.occurrence, self.confirmed_value, self.unit_measurement)
        elif self.auto_value:
            return '{0} ({1}) = {2} {3}'.format(self.type, self.occurrence, self.auto_value, self.unit_measurement)
        else:

src/geonode_odyssey/views.py
from django.shortcuts import render
from archaeology.models import Occurrence, Site

def index(request):
    num_sites = Site.objects.all().count()
    num_occurrences = Occurrence.objects.all().count()
    context = {
        'num_sites': num_sites,
        'num_occurrences': num_occurrences,
    }
    return render(request, "site_index.html", context=context)

src/geonode_odyssey/templates/archaeology/create_site.html
{% extends "geonode_base.html" %}
{% load staticfiles %}

{% load leaflet_tags %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block title %}
{% trans "Create Site" %}
{% endblock %}

{% block extra_head %}
<link href="{{ STATIC_URL }}css/site_base.css" rel="stylesheet"/>
{{ site.media.css }}
{{ occurrence.media.css }}
<style>
    select { width: 100% }
</style>
{% endblock %}


{% block body %}

{% leaflet_css plugins="forms" %}
{% leaflet_js plugins="forms" %}

<div class="page-header">
    <h2 class="page-title">{% trans "Add New Archaeological Site" %}</h2>
</div>

<div class="container">
    <form action="" method="post">
        {% csrf_token %}
        {{ site|crispy }}
        <div class="page-header">
            <h2>{% trans "Occurrence" %}</h2>
        </div>
        {{ occurrence|crispy }}
        <input type="submit" value={% trans "Add" %} class="btn btn-success"/>
    </form>
</div>
<br>  
{% endblock %}

{% block extra_script %}
{{ site.media.js }}
{{ occurrence.media.js }}
{% endblock %}

src/geonode_odyssey/templates/archaeology/delete_execution.html
{% extends "geonode_base.html" %}
{% load i18n %}
{% load class_tag %}

{% block title %}
{% trans "Delete - " %} {{item}}
{% endblock %}

{% block body %}
<div class="container" style="min-height:45vh;">
    <div class="page-header">
        <h2 class="page-title">{% trans "Remove Execution Log " %}{{item.name}}</h2>
    </div>
    <div class="row">
        <div class="col-md-8">
        <p class="lead">
            {% trans "Are you sure you want to delete" %} <a href="{{ item.get_absolute_url }}">{{ item }}</a>?
            </p>
            <form action="{% url 'delete_execution' item.id %}" method="post">
                {% csrf_token %}
                <a class="btn btn-default" href="{% url 'view_execution' item.id %}">{% trans "No, don't remove it" %}</a>
                <input type="submit" value="{% trans "Yes, I am sure" %}" class="btn btn-danger"/>
            </form>
        </div>
    </div>
</div>
{% endblock %}

src/geonode_odyssey/templates/archaeology/execution_detail.html
{% extends "geonode_base.html" %}
{% load leaflet_tags %}
{% load geojson_tags %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block title %}
{{execution.name}}
{% endblock %}

{% block extra_head %}
<link href="{{ STATIC_URL }}css/site_base.css" rel="stylesheet"/>
<style>
    .mrg-btm{
        margin-bottom: 10px;
    }
    .mrg-top{
        margin-top: 10px;
    }
</style>
{% leaflet_js %}
{% leaflet_css %}
{% endblock %}

{% block body %}
<div class="page-header">
    <h2 class="page-title">{{execution.name}}</h2>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-9">
            <div class="mrg-btm">
            {% leaflet_map "map" callback="map_init" %}
            </div>
             <!-- Nav tabs -->
            <ul class="nav nav-tabs">
                <li class="nav-item active">
                <a class="nav-link active" data-toggle="tab" href="#info"><i class="fa fa-info-circle"></i> {% trans "Info" %}</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#layers"><i class="fa fa-align-justify"></i> {% trans "Layers Used" %}</a>
                </li>
                {% if execution.purpose == 'inference' %} 
                    <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#occurrences"><i class="fa fa-map-pin"></i> {% trans "Detections" %}</a>
                    </li>
                {% endif %}
            </ul>
            <!-- Tab panes -->
            <div class="tab-content">
                <div class="tab-pane active mrg-top" id="info">
                    <dl class="dl-horizontal">
                        <dt>{% trans "Name" %}</dt>
                        <dd>{{execution.name}}</dd>
                        <dt>{% trans "Date of Execution" %}</dt>
                        <dd>{{execution.executed_at}}</dd>
                        <dt>{% trans "Executed by" %}</dt>
                        <dd><a href="{{execution.executed_by.get_absolute_url}}">{{execution.executed_by}}</a></dd>
                        <dt>{% trans "Status" %}</dt>
                        <dd>{{ execution.get_status_display }}</dd>
                        <dt>{% trans "Purpose" %}</dt>
                        <dd>{{ execution.get_purpose_display }}</dd>
                        {% if execution.purpose == 'inference' %} 
                            <dt>{% trans "Total Detections" %}</dt>
                            <dd>{{ total_detections }}</dd>
                        {% endif %}
                    </dl>
                </div>
                <div class="tab-pane mrg-top" id="layers">
                    <table class="table table-striped table-bordered table-condensed">
                        <thead>
                            <th>{% trans "Layers" %}</th>
                        </thead>
                        <tbody>
                            {% for layer in execution.layers_used.all %}
                            <tr>
                                <td><a href="{{layer.upload_session.resource.get_absolute_url}}">{{layer.name}}</a></td>
                            </tr>
                            {% empty %}
                                <h5>{% trans "No layers!" %}</h5>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% if execution.purpose == 'inference' %} 
                <div class="tab-pane mrg-top" id="occurrences">
                    <table class="table table-striped table-bordered table-condensed">
                        <thead>
                            <th>{% trans "Occurrence" %}</th>
                            <th>{% trans "Status" %}</th>
                        </thead>
                        <tbody>
                            {% for occurrence in occurrences %}
                            <tr>
                                <td><a href="{% url 'view_occurrence' occurrence.id %}">{{occurrence.designation}}</a></td>
                                <td>{{occurrence.get_status_occurrence_display}}</td>
                            </tr>
                            {% empty %}
                                <h5>{% trans "No detections!" %}</h5>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% endif %}
            </div> 
        </div>
        <div class="col-md-3">
            <ul class="list-group">
                <li class="list-group-item">
                    <a class="btn btn-danger  btn-md btn-block" href="{% url 'delete_execution' execution.id %}">{% trans "Delete" %}</a>
                </li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block extra_script %}
<script>
  function map_init (map, options) {
    polygon = L.geoJson({{ execution.aoi|geojsonfeature|safe}}).addTo(map);
    var group = new L.featureGroup([polygon, ]);
    map.fitBounds([group.getBounds().getSouthWest(),group.getBounds().getNorthEast()]);
  }
</script>
{% endblock %}

src/geonode_odyssey/templates/archaeology/executions_history.html
{% extends "geonode_base.html" %}
{% load i18n %}
{% load leaflet_tags %}

{% block title %}
{% trans "Executions History" %}
{% endblock %}

{% block extra_head %}
<link href="{{ STATIC_URL }}css/site_base.css" rel="stylesheet"/>
<style>   
    .btn {
        margin-bottom: 5px;
    }
    
    .grid {
        position: relative;
        width: 100%;
        background: #fff;
        color: #666666;
        border-radius: 2px;
        margin-bottom: 25px;
        box-shadow: 0px 1px 4px rgba(0, 0, 0, 0.1);
    }
    
    .grid .grid-body {
        padding: 15px 20px 15px 20px;
        font-size: 0.9em;
        line-height: 1.9em;
    }

    .show {
      display: none;
    }
</style>
{% leaflet_js %}
{% leaflet_css %}
{% endblock %}

{% block body %}
<div class="container">
<div class="row">
  <!-- BEGIN SEARCH RESULT -->
  <div class="col-md-12">
    <div class="grid search">
      <div class="grid-body">
        <div class="row">
          <!-- BEGIN FILTERS -->
          <div class="col-md-3">
            <h4><i class="fa fa-bar-chart"></i> {% trans "Statistics" %}</h4>
            <ul style="list-style-type: none; padding: 0;">
            <li>{% trans "Not Verified:" %} {% widthratio not_verified_occurrences total_occurrences 100 %}%</li>
            <li>{% trans "Verified - False Positive:" %} {% widthratio false_positive_occurrences total_occurrences 100 %}%</li>
            <li>{% trans "Verified - True Positive:" %} {% widthratio true_positive_occurrences total_occurrences 100 %}%</li>
            </ul>
            <hr>
            <form action="" method="get" id="searchForm">
            <!-- BEGIN FILTER BY CATEGORY -->
            <h4><i class="fa fa-filter"></i> {% trans "Filters" %}</h4>
            <div class="form-check">
              <input class="form-check-input" type="radio" name="searchBy" id="searchBy1" value="name" {% if "name" == values.searchBy or not values.searchBy %}checked{% endif %}>
              <label class="form-check-label" for="searchBy1">{% trans "Name" %}</label>
            </div>
            <div class="form-check">
              <input class="form-check-input" type="radio" name="searchBy" id="searchBy5" value="extent" {% if "extent" == values.searchBy %}checked{% endif %}>
              <label class="form-check-label" for="searchBy5">{% trans "Extent" %}</label>
            </div>            
            <!-- END FILTER BY CATEGORY -->
            
            <div class="padding"></div>
            <div class="show">
            <!-- BEGIN FILTER BY EXTENT -->
              <h4>{% trans "Extent" %}:</h4>
              <button class="btn btn-primary" type="submit">{% trans "Search" %}</button>
              {% leaflet_map "extent" callback="map_init" %}
              <input type="hidden" id="coordinates" name="coordinates"> 
            </div>
            <!-- END FILTER BY EXTENT -->
          </div>
          <!-- END FILTERS -->
          <!-- BEGIN RESULT -->
          <div class="col-md-9">
            <h2><i class="fa fa-history"></i>{% trans " Execution History of the Automatic Identification" %}</h2>
            <hr>
            <!-- BEGIN SEARCH INPUT -->
            <div class="input-group">
              <input type="text" class="form-control" name="text" value="{{ values.text }}">
              <span class="input-group-btn">
                <button class="btn btn-primary" type="submit"><i class="fa fa-search"></i></button>
              </span>
            </div>
          
            <!-- END SEARCH INPUT -->
            {% if values.searchBy == "extent" %}
            <p>{% trans "Showing " %}{{count}} {% trans "result" %}{{ count|pluralize }} {% trans "matching the geographical extent" %}</p>
            {% elif values.text %}
              <p>{% trans "Showing " %}{{count}} {% trans "result" %}{{ count|pluralize }} {% trans "matching" %} "{{ values.text }}"</p>
            {% else %}
              <p>{% trans "Showing all results" %}</p>
            {% endif %}
            
            <div class="padding"></div>
            
            <div class="row">
              <!-- BEGIN ORDER RESULT -->
              <div class="form-group">
                <select class="btn btn-default pull-right" name="orderBy" onchange='this.form.submit();'>
                  <option value="" disabled selected hidden>{% trans "Order by" %}</option>
                  <option value="recent" {% if "recent" == values.orderBy%}selected{% endif %}>{% trans "Most recent" %}</option>
                  <option value="older" {% if "older" == values.orderBy%}selected{% endif %}>{% trans "Less recent" %}</option>
                  <option value="name_asc" {% if "name_asc" == values.orderBy%}selected{% endif %}>{% trans "Name (A - Z)" %}</option>
                  <option value="name_desc" {% if "name_desc" == values.orderBy%}selected{% endif %}>{% trans "Name (Z - A)" %}</option>
                </select>
              </div> 
              </div>
              <!-- END ORDER RESULT -->
            
            </form>
            <!-- BEGIN TABLE RESULT -->
            {% if count == 0 %}
              <h3>{% trans "No results found." %}</h3>
            {% else %}
            
            <div class="table-responsive">
              <table class="table table-hover">
                <thead>
                  <tr>
                    <th>{% trans "Name" %}</th>
                    <th class="text-right">{% trans "Purpose" %}</th>
                    <th class="text-right">{% trans "Status" %}</th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                  {% for execution in executions %}
                  <tr>
                  <td><a href="{% url 'view_execution' execution.id %}"><strong>{{execution.name}}</strong></a><br>{{execution.executed_at}}</td>
                  <td class="text-right">{{execution.get_purpose_display}}</td>
                  <td class="text-right">{{execution.get_status_display}}</td>
                </tr>
                {% endfor %}
              </tbody></table>
            </div>
            <!-- END TABLE RESULT -->
            
            <!-- BEGIN PAGINATION -->
            {% if executions.has_other_pages %}
            <ul class="pagination">
              {% if executions.has_previous %}
              <li class="page-item"><a class="page-link" href="?page={{ executions.previous_page_number }}&{{path}}">&laquo;</a></li>
              {% else %}
              <li class="page-item disabled"><a class="page-link" href="" tabindex="-1">&laquo;</a></li>
              {% endif %}
              {% for i in executions.paginator.page_range %}
              {% if executions.number == i %}
                <li class="page-item active"><a class="page-link" href="?page={{ i }}&{{path}}">{{ i }} <span class="sr-only">(current)</span></a></li>
              {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}&{{path}}">{{ i }}</a></li>
              {% endif %}
              {% endfor %}
              {% if executions.has_next %}
              <li class="page-item"><a class="page-link" href="?page={{ executions.next_page_number }}&{{path}}">&raquo;</a></li>
              {% else %}
              <li class="page-item disabled"><a class="page-link" href="" tabindex="-1">&raquo;</a></li>
              {% endif %}
            </ul>
            {% endif %}
            <!-- END PAGINATION -->
            {% endif %}
          </div>
          <!-- END RESULT -->
        </div>
      </div>
    </div>
  </div>
  <!-- END SEARCH RESULT -->
</div>
</div>

{% endblock %}

{% block extra_script %}
<script>

  function map_init (map, options) {
    var url = new URL(window.location.href);
    var coord = url.searchParams.get("coordinates");
    if (coord != null){
      var array = coord.split(',');
      var corner1 = L.latLng(array[1], array[0]);
      var corner2 = L.latLng(array[3], array[2]);
      var bounds = L.latLngBounds(corner1, corner2);
      map.fitBounds(bounds);
    }
    document.getElementById("coordinates").value = map.getBounds().toBBoxString();
    map.on('moveend', function() { 
      document.getElementById("coordinates").value = map.getBounds().toBBoxString();
      //Causes a form submit loop since this event is fired with the fitBound method
      //document.getElementById("searchForm").submit();
    });
  }

  $(window).on('load', function(){
    if ($("#searchBy5").is(':checked')) {
      $('.show').removeClass("hidden");
    } else {
      $('.show').addClass("hidden");
    }
  });

  $(".form-check input[type='radio']").on("change", function() {
     if ($("#searchBy5").is(':checked')) {
       $('.show').removeClass("hidden");
     } else {
       $('.show').addClass("hidden");
     }
   })
</script>
{% endblock %}